package io.github.graphdsl.gradle

import io.github.graphdsl.gradle.task.GenerateDslTask
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.tasks.SourceSetContainer
import org.gradle.api.tasks.bundling.Jar
import org.gradle.kotlin.dsl.register
import org.jetbrains.kotlin.gradle.dsl.KotlinJvmProjectExtension
import io.github.graphdsl.gradle.GraphDslPluginCommon
import io.github.graphdsl.gradle.GraphDslPluginCommon.configureIdeaIntegration

/**
 * Gradle plugin that generates type-safe Kotlin DSL query builders from GraphQL schema.
 *
 * Apply this plugin to any project that has GraphQL schema files and wants to
 * use a Kotlin DSL for building queries.
 *
 * ## Usage
 *
 * ```kotlin
 * plugins {
 *     kotlin("jvm")
 *     id("io.github.graphdsl.graphdsl-gradle-plugin")
 * }
 *
 * graphDsl {
 *     packageName.set("com.example.api.dsl")
 *     schemaDir.set("src/main/graphql")
 * }
 * ```
 *
 * The plugin will:
 * 1. Scan for `.graphqls` files in the configured schema directory
 * 2. Generate Kotlin DSL source files into `build/generated-sources/graphdsl`
 * 3. Automatically add the generated sources to the Kotlin `main` source set
 */
class GraphDslPlugin : Plugin<Project> {
    override fun apply(project: Project): Unit = with(project) {
        val ext = extensions.create("graphDsl", GraphDslExtension::class.java, objects)

        val pluginClasspath = files(
            GraphDslPluginCommon.getClassPathElements(this@GraphDslPlugin::class.java)
        )

        val generateDslTask = tasks.register<GenerateDslTask>("generateGraphDsl") {
            mainClass.set(CODEGEN_MAIN_CLASS)
            classpath.setFrom(pluginClasspath)
            schemaFiles.setFrom(
                ext.schemaDir.map { dir ->
                    fileTree(layout.projectDirectory.dir(dir)) { include("**/*.graphqls") }
                }
            )
            packageName.set(ext.packageName)
            useBytecode.set(ext.useBytecode)
            // Output directory differs by mode: .kt source files vs .class bytecode files
            outputDirectory.set(
                ext.useBytecode.flatMap { useBytecode ->
                    layout.buildDirectory.dir(
                        if (useBytecode) "generated-classes/graphdsl" else "generated-sources/graphdsl"
                    )
                }
            )
        }

        // For bytecode mode, package the generated .class files into a JAR.
        // A JAR is required for Android (AGP doesn't support raw class directories as
        // implementation dependencies). The from() clause creates an implicit task dependency
        // on generateDslTask, so the JAR is always up to date.
        // This task is only wired into the compile classpath when useBytecode = true (see afterEvaluate).
        val packageGraphDslClassesTask = tasks.register<Jar>("packageGraphDslClasses") {
            description = "Packages GraphDSL-generated bytecode into a JAR for consumption."
            archiveBaseName.set("graphdsl-generated")
            includeEmptyDirs = false
            from(generateDslTask.flatMap { it.outputDirectory })
            destinationDirectory.set(layout.buildDirectory.dir("generated-jars/graphdsl"))
        }

        // Make compile tasks depend on generation
        tasks.matching { it.name == "compileKotlin" || it.name == "compileJava" }.configureEach {
            dependsOn(generateDslTask)
        }

        // IDE integration
        configureIdeaIntegration(generateDslTask)

        // Wire output into compilation after the user has configured the extension.
        afterEvaluate {
            val useBytecode = ext.useBytecode.getOrElse(false)

            pluginManager.withPlugin("org.jetbrains.kotlin.jvm") {
                if (useBytecode) {
                    project.dependencies.add(
                        "implementation",
                        project.files(packageGraphDslClassesTask.flatMap { it.archiveFile })
                    )
                } else {
                    val kotlinExt = extensions.getByType(KotlinJvmProjectExtension::class.java)
                    kotlinExt.sourceSets.named("main") {
                        kotlin.srcDir(generateDslTask.flatMap { it.outputDirectory })
                    }
                }
            }

            // Android: wire the generated JAR into all variant compile classpaths.
            // AGP requires a JAR (not a raw class directory) for implementation dependencies.
            pluginManager.withPlugin("org.jetbrains.kotlin.android") {
                if (useBytecode) {
                    project.dependencies.add(
                        "implementation",
                        project.files(packageGraphDslClassesTask.flatMap { it.archiveFile })
                    )
                    // Android compile task names follow the pattern compile{Variant}Kotlin.
                    // Wire them explicitly so the JAR is always built before compilation.
                    tasks.configureEach {
                        if (name.startsWith("compile") && name.endsWith("Kotlin")) {
                            dependsOn(packageGraphDslClassesTask)
                        }
                    }
                }
            }

            // Wire into Java compilation if Kotlin plugin isn't applied
            pluginManager.withPlugin("java") {
                if (!pluginManager.hasPlugin("org.jetbrains.kotlin.jvm")) {
                    if (useBytecode) {
                        project.dependencies.add(
                            "implementation",
                            project.files(packageGraphDslClassesTask.flatMap { it.archiveFile })
                        )
                    } else {
                        val sourceSets = extensions.getByType(SourceSetContainer::class.java)
                        sourceSets.named("main") {
                            java.srcDir(generateDslTask.flatMap { it.outputDirectory })
                        }
                    }
                }
            }
        }
    }

    companion object {
        private const val CODEGEN_MAIN_CLASS = "io.github.graphdsl.cli.KotlinDslGenerator\$Main"
    }
}
